#mapper文件的位置
mybatis:
  # 1.mapper.xml位置
  mapper-locations: classpath:/mappers/*.xml
  # 2.配置别名
  type-aliases-package: com.gxz.pojo
  configuration:
    # 2.驼峰式映射
    map-underscore-to-camel-case: true
    # 3.resultmap进行多层嵌套匹配
    auto-mapping-behavior: full
    # 4.日志输出
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl