#mapper文件的位置
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.gxz.pojo
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl