server:
  port: 8000 #端口号 默认8080
  servlet:
    context-path: /boot #根路径

#默认的静态资源路径为 classpath:/static或resources或public或META-INF/resources
spring:
  web:
    resources:
      static-locations: classpath:/webapp #设置静态资源文件夹